/**
* Name        : fibonacci_dynamic.S
* Author      : Name, Student Number, Section, CSCI 261, VIU
* Version     : 1.0.0
* Description : int fibonacci_dynamic(int fib_index) function,
* 		Accepts an index of fibonacci sequence (there is max limit
*		of the index) and computes the fibonacci sequence value of the
*		index using dynamic programming		
*/

/*
* Code segment and the codes
*/			
