/**
* Name        : fibonacci_sequence.S
* Author      : Name, Student Number, Section, CSCI 261, VIU
* Version     : 1.0.0
* Description : void fibonacci_sequence(int fibonacci_seq[], int max_index) function,
* 		Accepts an array to place fibonacci sequence values and a max index
*		of the array as its paramters.
*		Computes all the fibonacci sequence values for index 0 to max_index and
*		places the sequence values at appropriate position into the array.
*/

/*
* Code segment and the codes
*/
