/**
* Name        : show_fibonacci_seq.S
* Author      : Name, Student Number, Section, CSCI 261, VIU
* Version     : 1.0.0
* Description : void show_fibonacci_seq(int fibonacci_seq[], int max_index) function,
* 		Accepts an array of fibonacci sequence values and the max index
*		of the array as its paramters and prints the values from the array
*		on the screen.
*/

/*
* Data segment and the global variables in it
*/


/*
* Code segment and the codes
*/
